// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBld2hqOj2127h4a3txbL10BtRWECzktqM',
    appId: '1:1081521546102:web:7185f7c5a0bbf11ec81057',
    messagingSenderId: '1081521546102',
    projectId: 'physiotherapy-app-d75ed',
    authDomain: 'physiotherapy-app-d75ed.firebaseapp.com',
    databaseURL: 'https://physiotherapy-app-d75ed-default-rtdb.firebaseio.com',
    storageBucket: 'physiotherapy-app-d75ed.appspot.com',
    measurementId: 'G-VGF2J6ZLSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzmWx6tErmjLf8-B2khpianyxsYkvlQbs',
    appId: '1:1081521546102:android:18bd4f46e9959a0ec81057',
    messagingSenderId: '1081521546102',
    projectId: 'physiotherapy-app-d75ed',
    databaseURL: 'https://physiotherapy-app-d75ed-default-rtdb.firebaseio.com',
    storageBucket: 'physiotherapy-app-d75ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIVnpXash-Pf3bNxK_H6LWCpAfpAn9J3c',
    appId: '1:1081521546102:ios:2859b0103facecf7c81057',
    messagingSenderId: '1081521546102',
    projectId: 'physiotherapy-app-d75ed',
    databaseURL: 'https://physiotherapy-app-d75ed-default-rtdb.firebaseio.com',
    storageBucket: 'physiotherapy-app-d75ed.appspot.com',
    androidClientId: '1081521546102-k2ubqdot1nuqj95v532ej01qf8mjggf5.apps.googleusercontent.com',
    iosClientId: '1081521546102-v4ce46fv3gdaa6p2urgoh0tth7s61e16.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalyearproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIVnpXash-Pf3bNxK_H6LWCpAfpAn9J3c',
    appId: '1:1081521546102:ios:2859b0103facecf7c81057',
    messagingSenderId: '1081521546102',
    projectId: 'physiotherapy-app-d75ed',
    databaseURL: 'https://physiotherapy-app-d75ed-default-rtdb.firebaseio.com',
    storageBucket: 'physiotherapy-app-d75ed.appspot.com',
    androidClientId: '1081521546102-k2ubqdot1nuqj95v532ej01qf8mjggf5.apps.googleusercontent.com',
    iosClientId: '1081521546102-v4ce46fv3gdaa6p2urgoh0tth7s61e16.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalyearproject',
  );
}
